Laboratory work #1, Aladyshkin Vasiliy - 20FPL3
fipl-hse/2021-2-level-labs pull request #42
Opened 2021-09-11 16:18 UTC by froschalad

2021-09-16 11:31 UTC, WhiteJaeger commented
It's time to push some changes. October 1st is coming

2021-09-21 07:05 UTC, WhiteJaeger commented
It's time to push some changes. October 1st is coming.

2021-09-26 18:14 UTC, WhiteJaeger requested changes

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +    if type(text) == str:
There should be a check for the input arguments at the top of the function - after the documentation string. Remove nesting here and extract the check into a separate `if` block earlier.

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +        tokens = [token for token in tokens if token not in stop_words]
Good.

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +    if type(tokens) == list:
There should be a check for the input arguments at the top of the function - after the documentation string. Remove nesting here and extract the check into a separate `if` block earlier.

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +    if type(freq_dict) == dict:
There should be a check for the input arguments at the top of the function - after the documentation string. Remove nesting here and extract the check into a separate `if` block earlier.

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +    if type(language) == str and type(text) == str and type(stop_words) == list:
There should be a check for the input arguments at the top of the function - after the documentation string. Remove nesting here and extract the check into a separate `if` block earlier.

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +    if type(unknown_profile) == dict and type(profile_to_compare) == dict and type(top_n) == int:
There should be a check for the input arguments at the top of the function - after the documentation string. Remove nesting here and extract the check into a separate `if` block earlier.

2021-09-26 18:14 UTC, WhiteJaeger commented on lab_1/main.py
> +                distance = len(shared_words) / len(top_of_unknown_profile)
Are you sure about calculating the distance on each iteration of the `for word in top_of_unknown_profile:` loop?

2021-09-28 15:10 UTC, froschalad commented
what is wrong with "unittests"?

2021-09-28 18:12 UTC, WhiteJaeger requested changes

2021-09-28 18:12 UTC, WhiteJaeger commented on lab_1/main.py
> +    if not isinstance((language, text), str) or not isinstance(stop_words, list):
` isinstance((language, text), str)` does not work like that. `isinstance` supports only one object at a time. Split into several checks.

2021-09-28 18:12 UTC, WhiteJaeger commented on lab_1/main.py
> +    if not isinstance((unknown_profile, profile_to_compare), dict) or not isinstance(top_n, int):
`isinstance` supports only one object at a time. Split into several checks.

2021-09-28 18:12 UTC, WhiteJaeger commented on lab_1/main.py
> +    if not isinstance((unknown_profile, profile_1, profile_2), dict) or not isinstance(top_n, int):
`isinstance` supports only one object at a time. Split into several checks.

2021-09-28 18:13 UTC, WhiteJaeger commented
I do not see any changes in `start.py`.

2021-10-05 14:35 UTC, closed without merging