Laboratory work #1, Golovleva Yekaterina - 20FPL3
fipl-hse/2021-2-level-labs pull request #49
Opened 2021-09-13 21:07 UTC by esgolovleva

2021-09-16 11:32 UTC, WhiteJaeger commented
It's time to push some changes. October 1st is coming

2021-09-21 06:54 UTC, WhiteJaeger commented
It's time to push some changes. October 1st is coming.

2021-09-26 13:18 UTC, esgolovleva commented
Some style mistakes cannot be fixed!

2021-09-26 18:43 UTC, WhiteJaeger requested changes
Good overall yet you should clean up the `main.py` file. 

`i`, `x` and such are not very descriptive names for a variable, are they?

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> +        return None
These checks could be combined.

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> -def detect_language(unknown_profile: dict, profile_1: dict, profile_2: dict, top_n: int) -> str or None:
Why change the interface?

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> +        return None
Could be merged.

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> +def detect_language(unknown_profile: dict, profile_1: dict, profile_2: dict, top_n: int):
Why change the interface?

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> -def compare_profiles_advanced(unknown_profile: dict, profile_to_compare: dict, top_n: int) -> list or None:
Why change the interface?

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> +def compare_profiles_advanced(unknown_profile: dict, profile_to_compare: dict, top_n: int):
Why change the interface?

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> +def detect_language_advanced(unknown_profile: dict, profiles: list, languages: list, top_n: int):
Why change the interface?

2021-09-26 18:43 UTC, WhiteJaeger commented on lab_1/main.py
> +    if len(scores) == 0:
Could be simplified.

2021-09-28 12:38 UTC, esgolovleva commented
1. Variables have been renamed with more descriptive names.
2. The function descriptions are back in place (interface).
3. The checks for the correctness of the entered data have been combined.
4. The part of the code that needed to be simplified has been simplified.

2021-09-28 18:20 UTC, WhiteJaeger approved these changes

2021-10-05 14:42 UTC, closed without merging